//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 09:52:50 PM SAMT 
//


package ru.geekbrains.AMorozov.market.soap.soapcategory;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="soapCategory" type="{http://www.amorozov.com/spring/ws/soapCategory}soapCategory"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "soapCategory"
})
@XmlRootElement(name = "getCategoryByIdResponse")
public class GetCategoryByIdResponse {

    @XmlElement(required = true)
    protected SoapCategory soapCategory;

    /**
     * Gets the value of the soapCategory property.
     * 
     * @return
     *     possible object is
     *     {@link SoapCategory }
     *     
     */
    public SoapCategory getSoapCategory() {
        return soapCategory;
    }

    /**
     * Sets the value of the soapCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoapCategory }
     *     
     */
    public void setSoapCategory(SoapCategory value) {
        this.soapCategory = value;
    }

}
