//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 09:52:50 PM SAMT 
//


package ru.geekbrains.AMorozov.market.soap.soapcategory;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amorozov.spring.ws.soapcategory package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amorozov.spring.ws.soapcategory
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCategoryByIdRequest }
     * 
     */
    public GetCategoryByIdRequest createGetCategoryByIdRequest() {
        return new GetCategoryByIdRequest();
    }

    /**
     * Create an instance of {@link GetCategoryByIdResponse }
     * 
     */
    public GetCategoryByIdResponse createGetCategoryByIdResponse() {
        return new GetCategoryByIdResponse();
    }

    /**
     * Create an instance of {@link SoapCategory }
     * 
     */
    public SoapCategory createSoapCategory() {
        return new SoapCategory();
    }

}
