//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 09:52:50 PM SAMT 
//


package ru.geekbrains.AMorozov.market.soap.soapproduct;

import ru.geekbrains.AMorozov.market.models.Product;

import javax.xml.bind.annotation.*;
import java.util.Optional;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="soapProduct" type="{http://www.amorozov.com/spring/ws/soapProduct}soapProduct"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "soapProduct"
})
@XmlRootElement(name = "getProductByIdResponse")
public class GetProductByIdResponse {

    @XmlElement(required = true)
    protected SoapProduct soapProduct;

    /**
     * Gets the value of the soapProduct property.
     * 
     * @return
     *     possible object is
     *     {@link SoapProduct }
     *
     * @param byId
     */
    public SoapProduct getSoapProduct(Optional<Product> byId) {
        return soapProduct;
    }

    /**
     * Sets the value of the soapProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoapProduct }
     *     
     */
    public void setSoapProduct(SoapProduct value) {
        this.soapProduct = value;
    }

}
